# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql
  pool: 5
  timeout: 5000
  host: localhost
  port: 3306

development:
  <<: *default
  username: root
  password: 123456
  database: dev_
test:
  <<: *default
  database: test_

production:
  <<: *default
  database: prod_
